version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: deportes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mi_clave_segura
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_NAME: deportes_db
      DB_USER: postgres
      DB_PASS: mi_clave_segura
      DB_HOST: db
      DB_PORT: 5432
      NODE_ENV: development
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  pgdata: