### Test ServiceA through Gateway (Round Robin Load Balancing)
GET http://localhost:8080/api/personas/getUsuarios
Accept: application/json


### Test ServiceA through Gateway (Round Robin Load Balancing)
GET http://localhost:8080/api/nacionalidad/
Accept: application/json




### Test ServiceA through Gateway (Round Robin Load Balancing)
POST http://localhost:8080/api/nacionalidad
Content-Type: application/json

{
  "pais": "Chile",
  "estado": false
}


### Test ServiceA through Gateway (Round Robin Load Balancing)
PUT http://localhost:8080/api/nacionalidad/1
Content-Type: application/json

{
  "pais": "Bolivia"
}

### Delete
DELETE http://localhost:8080/api/nacionalidad/3
Accept: application/json





###Get by id nacionalidad
GET http://localhost:8080/nacionalidad/getbyId
Content-Type: application/json
Accept: application/json


{
  "id":6
}

###Get by id nacionalidad Param
GET http://localhost:8080/nacionalidad/getbyId/5
Accept: application/json


### Test ServiceA through Gateway (Round Robin Load Balancing)
POST http://localhost:8080/api/personas/registro
Accept: application/json
Content-Type: application/json

{
  "persona": {
    "nombre": "Javier",
    "ci":"71506101",
    "genero":"masculino",
    "fnac":"1993-07-10",
    "ap": "Gómez",
    "am":"Avila",
    "id_nacionalidad": 1
  },
  "usuario": {
    "email": "javier@gmail.com",
    "password": "secreta12345",
    "rol":"admin"
  }
}





### Auth
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "javier@gmail.com",
  "password": "secreta12345"
}